//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RinconLetrasBDEntities1 : DbContext
    {
        public RinconLetrasBDEntities1()
            : base("name=RinconLetrasBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Autores> Tb_Autores { get; set; }
        public virtual DbSet<Tb_DetallesFacturas> Tb_DetallesFacturas { get; set; }
        public virtual DbSet<Tb_Editoriales> Tb_Editoriales { get; set; }
        public virtual DbSet<Tb_Facturas> Tb_Facturas { get; set; }
        public virtual DbSet<Tb_Generos> Tb_Generos { get; set; }
        public virtual DbSet<Tb_Libros> Tb_Libros { get; set; }
        public virtual DbSet<Tb_Roles> Tb_Roles { get; set; }
        public virtual DbSet<Tb_Ubicacion> Tb_Ubicacion { get; set; }
        public virtual DbSet<Tb_Ubicaciones> Tb_Ubicaciones { get; set; }
        public virtual DbSet<Tb_Usuarios> Tb_Usuarios { get; set; }
        public virtual DbSet<Tb_Nacionalidades> Tb_Nacionalidades { get; set; }
    
        public virtual int RegistrarCliente(string nombreUsuario, Nullable<System.DateTime> fechaNacimiento, Nullable<int> identificacion, string correoElectronico, string contrasena)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var identificacionParameter = identificacion.HasValue ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(int));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarCliente", nombreUsuarioParameter, fechaNacimientoParameter, identificacionParameter, correoElectronicoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<ValidarUsuario_Result> ValidarUsuario(string correoElectronico, string contrasenna)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidarUsuario_Result>("ValidarUsuario", correoElectronicoParameter, contrasennaParameter);
        }
    
        public virtual ObjectResult<ConsultarCatalogoLibros_Result> ConsultarCatalogoLibros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCatalogoLibros_Result>("ConsultarCatalogoLibros");
        }
    
        public virtual int RegistrarEmpleado(string nombreUsuario, Nullable<System.DateTime> fechaNacimiento, Nullable<int> identificacion, string correoElectronico, string contrasenna, Nullable<int> idRol)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var identificacionParameter = identificacion.HasValue ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(int));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("IdRol", idRol) :
                new ObjectParameter("IdRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarEmpleado", nombreUsuarioParameter, fechaNacimientoParameter, identificacionParameter, correoElectronicoParameter, contrasennaParameter, idRolParameter);
        }
    }
}
