//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RinconLetrasBDEntities : DbContext
    {
        public RinconLetrasBDEntities()
            : base("name=RinconLetrasBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Autores> Tb_Autores { get; set; }
        public virtual DbSet<Tb_Clientes> Tb_Clientes { get; set; }
        public virtual DbSet<Tb_Editoriales> Tb_Editoriales { get; set; }
        public virtual DbSet<Tb_Empleados> Tb_Empleados { get; set; }
        public virtual DbSet<Tb_Generos> Tb_Generos { get; set; }
        public virtual DbSet<Tb_Libros> Tb_Libros { get; set; }
        public virtual DbSet<Tb_Puestos> Tb_Puestos { get; set; }
        public virtual DbSet<Tb_Ubicacion> Tb_Ubicacion { get; set; }
        public virtual DbSet<Tb_Ubicaciones> Tb_Ubicaciones { get; set; }
    
        public virtual int RegistrarCliente(string nombreCliente, Nullable<long> tarjetaCliente, string correo)
        {
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("NombreCliente", nombreCliente) :
                new ObjectParameter("NombreCliente", typeof(string));
    
            var tarjetaClienteParameter = tarjetaCliente.HasValue ?
                new ObjectParameter("TarjetaCliente", tarjetaCliente) :
                new ObjectParameter("TarjetaCliente", typeof(long));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarCliente", nombreClienteParameter, tarjetaClienteParameter, correoParameter);
        }
    
        public virtual ObjectResult<ValidarEmpleado_Result> ValidarEmpleado(string correoElectronico, string contrasenna)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidarEmpleado_Result>("ValidarEmpleado", correoElectronicoParameter, contrasennaParameter);
        }
    }
}
