//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Autores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Autores()
        {
            this.Tb_Libros = new HashSet<Tb_Libros>();
        }
    
        public int IdAutor { get; set; }
        public string Nombre_Autor { get; set; }
        public string Nacionalidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Libros> Tb_Libros { get; set; }
    }
}
