//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Clientes
    {
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public int TarjetaCliente { get; set; }
        public string Correo { get; set; }
    }
}
