//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DetallesFacturas
    {
        public int IdFactura { get; set; }
        public int Id_libro { get; set; }
        public Nullable<int> CantidadComprada { get; set; }
    
        public virtual Tb_Facturas Tb_Facturas { get; set; }
        public virtual Tb_Libros Tb_Libros { get; set; }
    }
}
