//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empleados
    {
        public int IdEmpleados { get; set; }
        public string NombreEmpleado { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<int> NumeroCarnet { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<int> Activo { get; set; }
        public string CorreoElectronico { get; set; }
        public string Contrasenna { get; set; }
    
        public virtual Tb_Puestos Tb_Puestos { get; set; }
    }
}
