//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Facturas()
        {
            this.Tb_DetallesFacturas = new HashSet<Tb_DetallesFacturas>();
        }
    
        public int IdFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public decimal MontoTotal { get; set; }
        public int IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetallesFacturas> Tb_DetallesFacturas { get; set; }
        public virtual Tb_Usuarios Tb_Usuarios { get; set; }
    }
}
