//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Libros()
        {
            this.Tb_DetallesFacturas = new HashSet<Tb_DetallesFacturas>();
            this.Tb_Ubicaciones = new HashSet<Tb_Ubicaciones>();
            this.Tb_Autores = new HashSet<Tb_Autores>();
        }
    
        public int IdLibro { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> CantidadInventario { get; set; }
        public Nullable<int> IdEditorial { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public bool Activo { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetallesFacturas> Tb_DetallesFacturas { get; set; }
        public virtual Tb_Editoriales Tb_Editoriales { get; set; }
        public virtual Tb_Generos Tb_Generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ubicaciones> Tb_Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Autores> Tb_Autores { get; set; }
    }
}
