//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Usuarios()
        {
            this.Tb_Facturas = new HashSet<Tb_Facturas>();
        }
    
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> Activo { get; set; }
        public string CorreoElectronico { get; set; }
        public string Contrasenna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Facturas> Tb_Facturas { get; set; }
        public virtual Tb_Roles Tb_Roles { get; set; }
    }
}
