//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLetras.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Ubicaciones
    {
        public int IdUbicacion { get; set; }
        public int IdLibro { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Tb_Libros Tb_Libros { get; set; }
        public virtual Tb_Ubicacion Tb_Ubicacion { get; set; }
    }
}
